--- yaml
# tasks file for agent 


      - name: Install zabbix on client machine
        yum:
          name:
            - zabbix
            - zabbix-agent
          enablerepo: zabbix-local
          state: present

      - name: edit parameters
        lineinfile:
          path: /etc/zabbix/zabbix_agentd.conf
          regexp: {{ item.key }}
          line: {{ item.value }}
          state: present
        with_items: '{{ agentconf }}'

      - name: start zabbix agent
        systemd:
          state: started
          enabled: yes
          name: zabbix-agent
      

















